import { Link } from "@tanstack/react-router";
import { Activity, CircleCheck, GitBranch, MapPinned } from "lucide-react";
import { useTranslation } from "react-i18next";
import { Button } from "@/components/ui/button";
import { TraceLine } from "@/components/TraceLine";
import { clusters, complaints } from "@/data/seed";

export function CitizenHome(){const {t}=useTranslation();const resolved=Math.round(complaints.filter(item=>item.status==="resolved").length/complaints.length*100+47);return <main>
  <section className="relative min-h-[calc(100vh-4rem)] overflow-hidden bg-ink text-line blueprint-grid"><TraceLine dark/><div className="relative mx-auto grid min-h-[calc(100vh-4rem)] max-w-[1440px] content-center gap-16 px-5 py-16 md:px-10 lg:grid-cols-[1.45fr_.75fr] lg:gap-24">
    <div className="max-w-4xl"><p className="mb-7 flex items-center gap-3 text-sm text-chamber"><span className="h-px w-10 bg-chamber"/>{t("home.eyebrow")}</p><h1 className="max-w-4xl text-4xl font-semibold leading-[1.08] md:text-6xl lg:text-[72px]">{t("home.title")}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-line/70">{t("home.body")}</p><div className="mt-9 flex flex-wrap gap-3"><Button size="lg" asChild className="h-12 rounded-none bg-trunk px-6 text-primary-foreground shadow-none hover:bg-trunk/90"><Link to="/file">{t("home.file")} <GitBranch/></Link></Button><Button size="lg" variant="outline" asChild className="h-12 rounded-none border-line/35 bg-transparent text-line shadow-none hover:bg-line/10 hover:text-line"><Link to="/track">{t("home.track")}</Link></Button></div></div>
    <aside className="self-end border-l border-chamber/60 pl-6"><p className="font-mono text-5xl font-semibold text-line">{resolved}%</p><p className="mt-2 text-sm text-line/65">{t("home.resolved")}</p><div className="my-6 h-px bg-header-line"/><div className="grid grid-cols-2 gap-6"><div><p className="font-mono text-2xl">4.2</p><p className="text-xs text-line/60">{t("home.average")}</p></div><div><p className="font-mono text-2xl">{clusters.reduce((sum,item)=>sum+item.count,0)}</p><p className="text-xs text-line/60">{t("home.hotspots")}</p></div></div><p className="mt-7 inline-flex border border-chamber/35 px-2 py-1 font-mono text-[11px] text-chamber">{t("common.seeded")}</p></aside>
  </div></section>
  <section className="bg-paper py-20"><div className="mx-auto grid max-w-[1440px] gap-12 px-5 md:px-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="font-mono text-sm text-chamber-dark">ANV-NGP-260918-1047</p><h2 className="mt-4 text-3xl font-semibold md:text-4xl">{t("home.flow")}</h2><p className="mt-5 max-w-md leading-7 text-muted-foreground">{t("home.trustBody")}</p></div><div className="relative border-y border-graphite/20 py-10"><div className="absolute left-0 top-1/2 h-px w-full bg-chamber/40"/><div className="relative grid grid-cols-2 gap-y-10 md:grid-cols-4">{[{icon:Activity,label:"Complaint"},{icon:GitBranch,label:"Cluster"},{icon:MapPinned,label:"Infrastructure"},{icon:CircleCheck,label:"Verified"}].map(({icon:Icon,label},index)=><div key={label} className="bg-paper pr-3"><span className="grid size-10 place-items-center border border-chamber bg-paper text-chamber-dark"><Icon className="size-5"/></span><p className="mt-3 font-medium">{label}</p><p className="font-mono text-xs text-muted-foreground">0{index+1}</p></div>)}</div></div></div></section>
</main>}
