import { useState } from "react";
import { useSearch } from "@tanstack/react-router";
import { CircleCheck, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ComplaintTimeline } from "@/components/ComplaintTimeline";
import { StatusBadge } from "@/components/StatusBadge";
import { complaints } from "@/data/seed";
export function TrackComplaint(){const search=useSearch({strict:false}) as {id?:string};const [id,setId]=useState(search.id??"ANV-NGP-260918-1047");const [active,setActive]=useState(search.id??"ANV-NGP-260918-1047");const [confirmed,setConfirmed]=useState(false);const item=complaints.find(c=>c.id===active)??complaints[0];return <main className="min-h-[calc(100vh-4rem)] bg-paper"><div className="mx-auto max-w-5xl px-5 py-12 md:px-10"><p className="font-mono text-sm text-chamber-dark">One ID · one public record</p><h1 className="mt-3 text-4xl font-semibold">Track a complaint</h1><form onSubmit={event=>{event.preventDefault();setActive(id)}} className="mt-8 flex max-w-2xl gap-2"><Input value={id} onChange={event=>setId(event.target.value)} className="h-12 rounded-none border-graphite/30 bg-card font-mono shadow-none focus-visible:ring-chamber"/><Button type="submit" size="icon" className="size-12 rounded-none bg-ink text-line hover:bg-ink/90" aria-label="Search tracking ID"><Search/></Button></form><div className="mt-10 grid gap-10 border-t border-graphite/20 pt-9 lg:grid-cols-[.72fr_1.28fr]"><section><StatusBadge band={item.severityBand} label={`${item.severity}/100 · ${item.urgency}`}/><h2 className="mt-5 text-2xl font-semibold">{item.title}</h2><p className="mt-3 leading-7 text-muted-foreground">{item.description}</p><dl className="mt-7 grid grid-cols-2 gap-5 border-y border-border py-5 text-sm"><div><dt className="text-muted-foreground">Department</dt><dd className="mt-1 font-medium">{item.department}</dd></div><div><dt className="text-muted-foreground">Zone</dt><dd className="mt-1 font-medium">{item.zone}</dd></div><div><dt className="text-muted-foreground">Cluster</dt><dd className="mt-1 font-mono">{item.clusterId??"Pending"}</dd></div><div><dt className="text-muted-foreground">Contractor</dt><dd className="mt-1 font-medium">{item.contractor}</dd></div></dl>{item.status==="resolved"&&<Button onClick={()=>setConfirmed(true)} disabled={confirmed} className="mt-6 rounded-none bg-chamber text-ink hover:bg-chamber/90">{confirmed?<><CircleCheck/>Resolution confirmed</>:"Confirm the issue is resolved"}</Button>}</section><section><h2 className="mb-7 text-xl font-semibold">Resolution thread</h2><ComplaintTimeline steps={item.timeline}/></section></div></div></main>}
